### ISSUE TITLE
Documentation for Customizing the ThemeManager

### ISSUE THREAD

**Issue by timunie** [MahApps/mahapps.com#9]
The ThemeManager can be overridden to customize the Theme generation. This should be documented. 

The question is: here or at ControlzEx? 

/cc @batzen

**Comment by batzen** [comment]
I guess most things regarding the ThemeManger should be documented at ControlzEx. Otherwise we'll end up with three sources of documentation (ControlzEx, MahApps.Metro and Fluent.Ribbon). Would be nice if someone could take care of writing the documentation as i am busy finalizing snoop 3.0, Fluent.Ribbon 8.0 and trying to improve the GlowWindow performance in ControlzEx.

**Comment by timunie** [comment]
I really would like to do this. But to be honest, I still don't understand what is going on there. I was testing and doing things for nearly a hole day and then somehow it worked magically. 😆 I have no idea if I did it correctly and I have no idea if I can do it again. I may try to analyze it deeper and write down my thoughts, but it will not be ready to publish. 

Have a great weekend
Tim

**Comment by timunie** [comment]
Ok I ll do it, @punker76 said it is ok to just post a sample, no need to understand in deep what is going on.

**Comment by punker76** [comment]
Wiki can be found [here](https://github.com/ControlzEx/ControlzEx/blob/develop/Wiki/ThemeManager.md)
